#!/bin/sh

for i in $1/*.jpg; do					
	year=`exiftime -tg $i | cut -f 3 -d ' ' | cut -f 1 -d : | sort`
	month=`exiftime -tg $i | cut -f 3 -d ' ' | cut -f 2 -d : | sort`
	if [ -d ./$year ]; then			
		if [ -d ./$year/$month ]; then	
			cp $i ./$year/$month	
		else				
			mkdir ./$year/$month	
			cp $i ./$year/$month	
		fi
	else					
		mkdir ./$year			
		mkdir ./$year/$month		
		cp $i ./$year/$month		
	fi
done
