#!/bin/sh

for i in $1/*.jpg; do					#running through jpg files only
	year=`exiftime -tg $i | cut -f 3 -d ' ' | cut -f 1 -d : | sort`
	month=`exiftime -tg $i | cut -f 3 -d ' ' | cut -f 2 -d : | sort`
	if [ -d ./$year ]; then				#if the year exists
		if [ -d ./$year/$month ]; then		#and the month exists
			cp $i ./$year/$month		#move the file to the folder
		else					#however if the month doesn't exist
			mkdir ./$year/$month		#create month
			cp $i ./$year/$month		#and move the file to it
		fi
	else						#however if the year doesn't exist
		mkdir ./$year				#create year
		mkdir ./$year/$month			#and then create month
		cp $i ./$year/$month			#and move the file to it
	fi
done
