#!/bin/sh

columns=$1  
shift
new=0

if [ $# -ne 0 ]; then	
	echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"
	echo "<html>"
		echo "<head>"
			echo "<title>Pictures</title>"
		echo "</head>"
			echo "<body>"
				echo "<h1>Pictures</h1>"
				echo "<table>"

				while [ $# -ne 0 ]; do					
					if [ -z `file $1 | grep -o "JPEG"` ]; then
						echo "$1: Invalid file argument" >&2	
						shift
					else
						echo "<tr>"
						while [ $new -lt $columns ]; do		
							if [ -z $1 ]; then		
								break
							elif [ `file $1 | grep -o "JPEG"` ]; then			
								echo "<td><img src=\"$1\" height=100></td>"
								shift
								new=`expr $new + 1`
							else
								echo "$1: Invalid file argument" >&2
								shift
							fi
						done
						new=0
						echo "</tr>"
					fi
				done
				echo "</table>"
			echo "</body>"
	echo "</html>"
fi
