#!/bin/sh

columns=$1
shift
new=0

echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"
echo "<html>"
	echo "<head>"
		echo "<title>Pictures</title>"
	echo "</head>"
	echo "<body>"
		echo "<h1>Pictures</h1>"
	for i in $1/*; do			
		echo "<h2>`basename $i`</h2>"	
		echo "<table>"
		pics=`echo $i/*/*.jpg`	
		set $pics			
		while [ $# -ne 0 ]; do
			echo "<tr>"
			while [ $new -lt $columns ]; do
				echo "<td><img src=\"$1\" height=100></td>"	
				shift
				new=`expr $new + 1`
			done
			new=0		
			echo "</tr>"
		done
		
		echo "</table>"
	done
	echo "</body>"
echo "</html>"
